// Code generated by PlainSQL. DO NOT EDIT.

package dbgen

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
)

type Executor interface {
	Exec(context.Context, string, ...any) (pgconn.CommandTag, error)
	Query(context.Context, string, ...any) (pgx.Rows, error)
}

type Queries struct {
	executor Executor
}

func New(executor Executor) *Queries {
	return &Queries{executor: &queryExecutor{Executor: executor}}
}

type Read interface {
	ListRecentPosts(ctx context.Context, limit int64) ([]ListRecentPostsRow, error)
}

type ReadWrite interface {
	Read
}

var _ Read = (*Queries)(nil)
var _ ReadWrite = (*Queries)(nil)

// ErrTransactionScope means callback context was used with a different query set.
var ErrTransactionScope = errors.New("plainsql: use the transaction callback's queries with its context")

// ErrNestedTransaction means a transaction was started with callback context.
var ErrNestedTransaction = errors.New("plainsql: cannot start another transaction with transaction callback context")

type transactionContextKey struct{}

// queryExecutor checks callback scope before forwarding calls to pgx.
// Its pointer identifies the query set supplied to the callback.
type queryExecutor struct {
	Executor
}

func (e *queryExecutor) Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error) {
	if scope := ctx.Value(transactionContextKey{}); scope != nil && scope != e {
		return pgconn.CommandTag{}, ErrTransactionScope
	}
	return e.Executor.Exec(ctx, sql, args...)
}

func (e *queryExecutor) Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error) {
	if scope := ctx.Value(transactionContextKey{}); scope != nil && scope != e {
		return nil, ErrTransactionScope
	}
	return e.Executor.Query(ctx, sql, args...)
}

// Store exposes pool-backed queries and callback transactions.
// Keep the pool open for the lifetime of the store.
type Store struct {
	*Queries
	pool *pgxpool.Pool
}

// NewStore uses pool for transactions. The caller remains responsible for closing it.
func NewStore(pool *pgxpool.Pool) *Store {
	return &Store{Queries: New(pool), pool: pool}
}

// ReadTx runs fn in a read-only transaction. It commits on success and rolls back
// on failure. Use the supplied context and queries during the callback.
func (s *Store) ReadTx(ctx context.Context, fn func(context.Context, Read) error) error {
	if ctx.Value(transactionContextKey{}) != nil {
		return ErrNestedTransaction
	}
	return pgx.BeginTxFunc(ctx, s.pool, pgx.TxOptions{AccessMode: pgx.ReadOnly}, func(tx pgx.Tx) error {
		queries := New(tx)
		return fn(context.WithValue(ctx, transactionContextKey{}, queries.executor), queries)
	})
}

// ReadTxValue runs fn in a read-only transaction and returns its value after a
// successful commit. It returns the zero value of T on any transaction error.
func (s *Store) ReadTxValue[T any](ctx context.Context, fn func(context.Context, Read) (T, error)) (T, error) {
	var value T
	err := s.ReadTx(ctx, func(ctx context.Context, q Read) error {
		var err error
		value, err = fn(ctx, q)
		return err
	})
	if err != nil {
		var zero T
		return zero, err
	}
	return value, nil
}

// ReadWriteTx runs fn in a read-write transaction. It commits on success and rolls
// back on failure. Use the supplied context and queries during the callback.
func (s *Store) ReadWriteTx(ctx context.Context, fn func(context.Context, ReadWrite) error) error {
	if ctx.Value(transactionContextKey{}) != nil {
		return ErrNestedTransaction
	}
	return pgx.BeginTxFunc(ctx, s.pool, pgx.TxOptions{AccessMode: pgx.ReadWrite}, func(tx pgx.Tx) error {
		queries := New(tx)
		return fn(context.WithValue(ctx, transactionContextKey{}, queries.executor), queries)
	})
}

// ReadWriteTxValue runs fn in a read-write transaction and returns its value after
// a successful commit. It returns the zero value of T on any transaction error.
func (s *Store) ReadWriteTxValue[T any](ctx context.Context, fn func(context.Context, ReadWrite) (T, error)) (T, error) {
	var value T
	err := s.ReadWriteTx(ctx, func(ctx context.Context, q ReadWrite) error {
		var err error
		value, err = fn(ctx, q)
		return err
	})
	if err != nil {
		var zero T
		return zero, err
	}
	return value, nil
}

var _ Read = (*Store)(nil)
var _ ReadWrite = (*Store)(nil)
