// Code generated by PlainSQL. DO NOT EDIT.

package dbgen

import (
	"context"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5"
)

type ListRecentPostsRow struct {
	Title     string
	Author    string
	CreatedAt time.Time
}

const listRecentPostsSQL = `SELECT
    p.title,
    coalesce(u.display_name, u.email) AS author,
    p.created_at
FROM posts AS p
JOIN users AS u ON u.id = p.user_id
ORDER BY p.created_at DESC, p.id DESC
LIMIT $1`

func (q *Queries) ListRecentPosts(ctx context.Context, limit int64) ([]ListRecentPostsRow, error) {
	rows, err := q.executor.Query(ctx, listRecentPostsSQL, limit)
	if err != nil {
		return nil, fmt.Errorf("query ListRecentPosts: execute: %w", err)
	}
	result, err := pgx.CollectRows(rows, func(row pgx.CollectableRow) (ListRecentPostsRow, error) {
		var result ListRecentPostsRow
		err := row.Scan(&result.Title, &result.Author, &result.CreatedAt)
		return result, err
	})
	if err != nil {
		return nil, fmt.Errorf("query ListRecentPosts: collect rows: %w", err)
	}
	return result, nil
}
